CLASS LHC_HISTORIAL DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEHISID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Historial~CalculateHisID .
ENDCLASS.

CLASS LHC_HISTORIAL IMPLEMENTATION.
  METHOD CALCULATEHISID.
  ENDMETHOD.
ENDCLASS.
